# Generated by Django 4.2.10 on 2024-03-16 15:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='text_on_page',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
