# Generated by Django 4.2.10 on 2024-03-16 18:25

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pagecontent_text_on_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='text_on_page',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
