# Generated by Django 4.2.10 on 2024-03-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Проданий товар', 'verbose_name_plural': 'Продані товари'},
        ),
    ]
